/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.estruturadados.academia.ghrapic;

import com.estruturadados.academia.controller.ListagemMatriculasViewController;
import com.estruturadados.academia.database.ConnectionFactory;
import com.estruturadados.academia.database.model.Aluno;
import com.estruturadados.academia.database.model.Matricula;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ListagemMatriculasView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListagemMatriculasView
     */
    private Connection connection;
    private ListagemMatriculasViewController controller;
    private int codAluno;
    public ListagemMatriculasView(int codAluno) {
        this.codAluno = codAluno;
        this.conectarBanco();
        initComponents();
        this.connection = connection;
        controller = new ListagemMatriculasViewController(connection);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelListagemMatriculas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabledDadosMatriculas = new javax.swing.JTable();
        jButtonExcluir = new javax.swing.JButton();

        setClosable(true);
        setTitle("Matrículas");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanelListagemMatriculas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTabledDadosMatriculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matrícula", "Código", "Aluno", "Data matrícula", "Dia Vencimento", "Data encerramento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabledDadosMatriculas);
        if (jTabledDadosMatriculas.getColumnModel().getColumnCount() > 0) {
            jTabledDadosMatriculas.getColumnModel().getColumn(0).setResizable(false);
            jTabledDadosMatriculas.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTabledDadosMatriculas.getColumnModel().getColumn(1).setResizable(false);
            jTabledDadosMatriculas.getColumnModel().getColumn(1).setPreferredWidth(10);
            jTabledDadosMatriculas.getColumnModel().getColumn(2).setResizable(false);
            jTabledDadosMatriculas.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTabledDadosMatriculas.getColumnModel().getColumn(3).setResizable(false);
            jTabledDadosMatriculas.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTabledDadosMatriculas.getColumnModel().getColumn(4).setResizable(false);
            jTabledDadosMatriculas.getColumnModel().getColumn(4).setPreferredWidth(50);
            jTabledDadosMatriculas.getColumnModel().getColumn(5).setResizable(false);
            jTabledDadosMatriculas.getColumnModel().getColumn(5).setPreferredWidth(50);
        }

        jButtonExcluir.setText("Voltar");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListagemMatriculasLayout = new javax.swing.GroupLayout(jPanelListagemMatriculas);
        jPanelListagemMatriculas.setLayout(jPanelListagemMatriculasLayout);
        jPanelListagemMatriculasLayout.setHorizontalGroup(
            jPanelListagemMatriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListagemMatriculasLayout.createSequentialGroup()
                .addGroup(jPanelListagemMatriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListagemMatriculasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonExcluir)))
                .addContainerGap())
        );
        jPanelListagemMatriculasLayout.setVerticalGroup(
            jPanelListagemMatriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListagemMatriculasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelListagemMatriculas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelListagemMatriculas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void conectarBanco() {
        try {
            connection = ConnectionFactory.getConnection();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        controller.listarMatriculas((DefaultTableModel) jTabledDadosMatriculas.getModel(), codAluno);
    }//GEN-LAST:event_formInternalFrameActivated

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        ControleDeAlunosView cdav = new ControleDeAlunosView();
        this.getParent().setVisible(false);
        cdav.setVisible(true);
    }//GEN-LAST:event_jButtonExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JPanel jPanelListagemMatriculas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabledDadosMatriculas;
    // End of variables declaration//GEN-END:variables
}
